CREATE DATABASE phpmybootstrap;
use phpmybootstrap;
CREATE USER 'phpmybootstrap'@'%' IDENTIFIED BY  'password';
GRANT USAGE ON * . * TO  'phpmybootstrap'@'%' IDENTIFIED BY  'password' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS phpmybootstrap
GRANT SELECT ON phpmybootstrap . * TO 'phpmybootstrap'@'%' IDENTIFIED BY  'password' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE TABLE IF NOT EXISTS phpmybootstrap.page ( id int(4) NOT NULL AUTO_INCREMENT, dpt int(2) NOT NULL, psn int(2) NOT NULL, vis tinyint(1) NOT NULL DEFAULT '1', nam varchar(40) NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;
INSERT INTO phpmybootstrap.page (id, dpt, psn, vis, nam) VALUES (1, 1, 1, 1, 'Home'), (2, 2, 2, 1, 'About'),(3, 3, 3, 1, 'Contact') ;
CREATE TABLE IF NOT EXISTS phpmybootstrap.section ( id int(8) NOT NULL AUTO_INCREMENT, page int(2) NOT NULL, psn int(4) NOT NULL, tag varchar(20) NOT NULL, cla varchar(128) DEFAULT NULL, dta text, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;
INSERT INTO phpmybootstrap.section (id, page, psn, tag, cla, dta) VALUES (1, 1, 1, 'h1', NULL, 'Home Page'), (2, 1, 2, 'p', 'lead', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'), (3, 2, 1, 'h1', NULL, 'About Us'), (4, 2, 2, 'p', 'lead', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. '), (5, 3, 1, 'h1', NULL, 'Contact Us'), (6, 3, 2, 'p', 'lead', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
